### ISSUE TITLE
Startlight ignores markdown lists

### ISSUE THREAD

**Issue by saschat** [bzr-sys/bazaar-website#10]
I should change the issue name to "HTML lists formatting is shit".

**Comment by paddyohanlon** [comment]
Lists look ok to me

![Screenshot 2024-05-03 at 09 03 12](https://github.com/bzr-sys/bazaar-website/assets/1014022/a6cb8bd5-55c7-4152-a97e-d83014ccd694)

**Comment by paddyohanlon** [comment]
Fine in mdx files too.
