### ISSUE TITLE
Website should know if a user is logged in

### ISSUE THREAD

**Issue by saschat** [bzr-sys/bazaar-website#17]
Have a dashboard button instead of a log in / sign up button.

**Comment by paddyohanlon** [comment]
Auth tokens are stored on the cloud.bzr.dev origin and aren't available on bzr.dev. A way to work around that seems to be to use as a proxy to access the localstorage of cloud.bzr.dev. The iframe would communicate with bzr.dev via postMessage. I haven't tested that.

@saschat  What priority would you give this?

**Comment by saschat** [comment]
Not high. I would however change the login button to an account symbol (upper body figurine) and point it to cloud.bzr.dev (instead of the login page).

**Comment by paddyohanlon** [comment]
We have a user icon on https://cloud.bzr.dev/

You mean to always show that icon, instead of a log in button?

**Comment by saschat** [comment]
Yes, but I prefer something like https://fontawesome.com/icons/user?f=classic&s=solid for login/account.

**Comment by paddyohanlon** [comment]
Ok. I'll take care of it.
